#!/bin/bash

# Check if there is anything staged for commit
if git diff --cached --quiet; then
  echo "Nothing staged for commit. Aborting tests and commit."
  exit 1
fi

# Check if there are any non-staged changes in the working directory
if ! git diff --quiet; then
  # Stash unstaged changes
  git stash -q --keep-index
  make test
  exit_code=$?
  # Restore stashed unstaged changes
  git stash pop -q
else
  make test
  exit_code=$?
fi

# If the tests fail, abort the commit
if [ $exit_code -ne 0 ]; then
  echo "Tests failed. Aborting commit."
  exit 1
fi
