#!/bin/bash

# Check if there is anything staged for commit
if git diff --cached --quiet; then
  echo "Nothing staged for commit. Aborting tests and commit."
  exit 1
fi

# Check if there are any non-staged changes in the working directory
if git diff --quiet; then
  make test
  exit_code=$?
  make coverage-report
else
  # Stash non-staged changes before testing, and pop after testing
  git stash -q --keep-index
  make test
  exit_code=$?
  make coverage-report
  git stash pop -q
fi

# If the tests fail, abort the commit
if [ $exit_code -ne 0 ]; then
  echo "Tests failed. Aborting commit."
  exit 1
fi
