#!/bin/bash

# Check if there are any changes in the working directory
if [[ $(git status --porcelain) ]]; then
  # Stash any changes before testing, and pop after testing
  git stash -q
  make format-check
  exit_code=$?
  git stash pop -q

else
  make format-check
  exit_code=$?
fi

exit $exit_code
